### ISSUE TITLE
Migrations doesn't work

### ISSUE THREAD

**Issue by Messhias** [openclassify/openclassify#739]
**Describe the bug**
The migration doesn't work.

**To Reproduce**
1. Go to: just download the project and try run follow the steps.
2. See error
``` SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = openclassify and table_name = default_migrations and table_type = 'BASE TABLE```

**Expected behavior**
The migration has been executed.

**Screenshots**
![Screenshot 2020-10-23 at 02 17 20](https://user-images.githubusercontent.com/1161283/96945517-e35c5200-14d5-11eb-8530-73e79f7e764b.png)

**Desktop (please complete the following information):**
 - OS: OSX latest applicable of the date of issue.

**Additional context**
Well, since the project was made using Laravel I don't see the point to change the migrations table to default_migrations, this is could be a problem for Laravel ecossystem and for updating the project.

**Comment by fatihalp** [comment]
it seems that you have connection problem wtih mysql in docker. If you user our docker file maybe it's outdated. @Messhias 

I just tried installation on cloud and there's no error.

**Comment by Messhias** [comment]
> it seems that you have connection problem wtih mysql in docker. If you user our docker file maybe it's outdated. @Messhias
> 
> I just tried installation on cloud and there's no error.

Hi @fatihalp thanks for your feedback.

By the way enjoying the thread, we'll gonna have a wiki seeing how to create themes?

Thank you.

**Comment by fatihalp** [comment]
Hi @Messhias we're using pyrocms module and theme system. You can just check pyrocms docs and videos ;)


https://pyrocms.com/help/addon-development/themes/creating-a-theme

**Comment by Messhias** [comment]
I found the issue:

On docker-compose file we need add the .env variable into the PHP container context (docker-compose after the version 3.4 needs to be add it manually).

And also make the implicit link to PHP + MySQL container to not have the containers IP's conflicts.

Like this:

```
php:
        env_file:
            - ./.env
        image: nanoninja/php-fpm
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./:/var/www/html"
        links:
            -   mysqldb
````
